# Generated by Django 3.1.7 on 2021-03-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservering',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=50)),
                ('datumTijd', models.DateTimeField()),
            ],
        ),
    ]
